name: Update Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --no-restore

      # Step 5: Run tests with coverage for each project
      - name: Run tests with coverage (Integration Tests)
        run: dotnet test ../../tests/PioConnection.Api.Tests.Intergration/PioConnection.Api.Tests.Intergration.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./testresults/integration

      - name: Run tests with coverage (Unit Tests)
        run: dotnet test ../../tests/PioConnection.Api.Tests.Unit/PioConnection.Api.Tests.Unit.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./testresults/unit

      # Step 6: (Optional) Run tests with coverage (Functional Tests) 
      # Uncomment if you have functional tests
      #- name: Run tests with coverage (Functional Tests)
      #  run: dotnet test ../../tests/PioConnection.Api.Tests.Functional/PioConnection.Api.Tests.Functional.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./testresults/functional

      # Step 7: Install ReportGenerator tool for report aggregation
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # Step 8: Merge and generate the final coverage report
      - name: Merge coverage reports and generate report
        run: |
          reportgenerator "-reports:testresults/integration/*/coverage.cobertura.xml" \
                          "-reports:testresults/unit/*/coverage.cobertura.xml" \
                          #"-reports:testresults/functional/*/coverage.cobertura.xml" \  # Uncomment if functional tests exist
                          "-targetdir:coverage" -reporttypes:Html,Cobertura
          
      # Step 9: Check the coverage directory for the generated report
      - name: List coverage directory contents
        run: ls -R coverage

      # Step 10: Upload combined coverage to Codecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura.xml
          flags: unittests
          name: total-code-coverage
          fail_ci_if_error: true

      # Step 11: Add or update the badge in README
      - name: Update coverage badge in README
        run: |
          sed -i 's|!\[Coverage\](.*)|![Coverage](https://codecov.io/gh/317jamtay317/YOUR_REPO_NAME/branch/master/graph/badge.svg)|g' README.md
      # Replace 'YOUR_REPO_NAME' with your actual repository name

      # Step 12: Commit updated README with the badge
      - name: Commit updated README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update coverage badge"
          git push
