name: Push To Docker HUB

on:
 workflow_dispatch:
 # workflow_run:
 #   workflows: [".NET Build and Test API"]
 #  types:
 #    - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Match your .NET version

    - name: Build the application
      run: dotnet build PioConnection.Docker.sln --configuration Release

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
       docker build -t jamtay317/pioconnection:${{ github.sha }} -f ./Dockerfile .
       docker tag jamtay317/pioconnection:${{ github.sha }} jamtay317/pioconnection:dev-latest


    - name: Push Docker image to Docker Hub
      run: |
       docker push jamtay317/pioconnection:${{ github.sha }}
       docker push jamtay317/pioconnection:dev-latest
